### PR TITLE
Test decoder idempotence

### LINKED ISSUE #366: Test decoder idempotence
idempotence meaning: if you run the decoder twice on a set of data, it shouldn't modify it the second time.

part of this is making all our transforms idempotent, which includes #359 and making `AddMetadata` idempotent.

Exception: `Deduplicate` is not idempotent, and does not need to be. To make it idempotent for testing use `--seenMessagesSource=none`.

### PR DESCRIPTION
**Pull request by jklukas**
Closes #366

### CODE REVIEW

File: ingestion-beam/src/test/java/com/mozilla/telemetry/DecoderMainTest.java [hunk 1]
```diff
@@ -116,4 +116,37 @@ public void testGzippedPayload() throws Exception {
...
+        "--errorOutputFileCompression=UNCOMPRESSED", "--geoCityDatabase=GeoLite2-City.mmdb",
+        "--schemasLocation=schemas.tar.gz", "--redisUri=" + redis.uri });
+
+    Decoder.main(new String[] { "--inputFileFormat=json", "--inputType=file", //
+        "--input=" + intermediateOutput + "*.ndjson", //
+        "--output=" + output, //
+        "--errorOutput=" + errorOutput, //
+        "--outputFileFormat=json", "--outputType=file", "--errorOutputType=file",
+        "--includeStackTrace=false", "--outputFileCompression=UNCOMPRESSED",
+        "--errorOutputFileCompression=UNCOMPRESSED", "--geoCityDatabase=GeoLite2-City.mmdb",
```
Comment (relud) [inline ingestion-beam/src/test/java/com/mozilla/telemetry/DecoderMainTest.java]: using `GeoLite2-City.mmdb` is going to conflict with #558, so that will need to be resolved in the pr merged second

Comment (jklukas) [reply ingestion-beam/src/test/java/com/mozilla/telemetry/DecoderMainTest.java]: Indeed
