### PR TITLE
Bug: accessing ValueProvider at runtime in writeFile

### LINKED ISSUE #258: Don't access ValueProviders at compile time
@whd reported a problem where missing `--output` on template compilation throws an exception about value not being available until runtime. And indeed the following line is executed at compile time rather than runtime, breaking the ValueProvider guarantees:

        DynamicPathTemplate pathTemplate = new DynamicPathTemplate(outputPrefix.get());

We should check for other calls to `.get()` on ValueProvider and ensure they're not happening at compile time. And add tests that exercise this.

### PR DESCRIPTION
**Pull request by jklukas**
Closes #258

### CODE REVIEW

File: ingestion-beam/src/main/java/com/mozilla/telemetry/options/OutputType.java [hunk 1]
```diff
@@ -115,19 +116,25 @@
...
-                .to(pathTemplate.staticPrefix).withNaming(placeholderValues -> Write.defaultNaming(
-                    pathTemplate.replaceDynamicPart(placeholderValues), format.suffix()))));
+        .compose(
+            input -> input.apply("fixedWindows", Window.into(FixedWindows.of(windowDuration)))
+                .apply("writeFile", FileIO.<List<String>, PubsubMessage>writeDynamic()
+                    // We can't pass the attribute map to by() directly since MapCoder isn't
+                    // deterministic;
+                    // instead, we extract an ordered list of the needed placeholder values.
+                    // That list is later available to withNaming() to determine output location.
+                    .by(message -> pathTemplate.get().extractValuesFrom(message.getAttributeMap()))
```
Comment (relud) [inline ingestion-beam/src/main/java/com/mozilla/telemetry/options/OutputType.java]: is it possible to do this type of thing later to make all our inputs use value providers? because that would be ideal imo.
