### PR TITLE
Remove jsonFieldName instead of bqFieldName

### LINKED ISSUE #1294: ingestion-sink undeliverable message: java.lang.NullPointerException: null
/CC @relud, there appears to be a persistent issue with telemetry live sink that will need to be addressed this week (or dropped and recovered from pbd, but we don't have an automated mechanism for that):

    {
     insertId: "ul5b6261edy7hygbk"

    jsonPayload: {
      endOfBatch: false

    instant: {
       epochSecond: 1590375717
       nanoOfSecond: 429000000
      }
      level: "ERROR"
      loggerFqcn: "org.apache.logging.slf4j.Log4jLogger"
      loggerName: "com.mozilla.telemetry.ingestion.sink.io.Pubsub$Read"
      message: "failed to deliver message"
      thread: "Gax-2"
      threadId: 25
      threadPriority: 5

    thrown: {
       commonElementCount: 0
       extendedStackTrace: "java.lang.NullPointerException: null
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.coerceToBqType(PubsubMessageToObjectNode.java:508) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:395) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:286) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:374) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:286) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:374) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:286) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:342) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:286) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:342) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:286) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload.apply(PubsubMessageToObjectNode.java:243) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.transform.PubsubMessageToObjectNode$Payload$WithOpenCensusMetrics.apply(PubsubMessageToObjectNode.java:114) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.io.Gcs$Write$Ndjson.encodeInput(Gcs.java:51) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.io.Gcs$Write$Ndjson.encodeInput(Gcs.java:34) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.util.BatchWrite.apply(BatchWrite.java:148) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.util.BatchWrite.apply(BatchWrite.java:26) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.config.SinkConfig$Output.apply(SinkConfig.java:128) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.mozilla.telemetry.ingestion.sink.config.SinkConfig$Output.apply(SinkConfig.java:109) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995) ~[?:1.8.0_252]
    	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137) ~[?:1.8.0_252]
    	at com.mozilla.telemetry.ingestion.sink.io.Pubsub$Read.lambda$new$2(Pubsub.java:46) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
    	at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:379) [google-cloud-pubsub-1.102.1.jar:1.102.1]
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
    	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
    "
       name: "java.lang.NullPointerException"
      }
     }

From my read, it appears `coerceToBqType` is receiving a `null` as its `JsonNode o` argument and `o.isNull()` is not having any of it. /CC @jklukas as well since he modified the code most recently.

### PR DESCRIPTION
**Pull request by relud**
when fields are null or sent to additional_properties

fixes #1294

### CODE REVIEW

File: ingestion-sink/src/main/java/com/mozilla/telemetry/ingestion/sink/transform/PubsubMessageToObjectNode.java [hunk 1]
```diff
@@ -265,7 +265,7 @@ private void transformForBqSchema(ObjectNode parent, List<Field> bqFields,
       final Map<String, Field> bqFieldMap = bqFields.stream()
           .collect(Collectors.toMap(Field::getName, Function.identity()));
 
-      for (String jsonFieldName : Sets.newHashSet(parent.fieldNames())) {
+      for (String jsonFieldName : Lists.newArrayList(parent.fieldNames())) {
         final JsonNode value = parent.get(jsonFieldName);
```
Comment (relud) [inline ingestion-sink/src/main/java/com/mozilla/telemetry/ingestion/sink/transform/PubsubMessageToObjectNode.java:269]: a crash frame like `{"ip": "0xf08425a","ip\u0000��": null,...}` was handling the `ip\u0000��` field first, which normalized the field name to `ip`, then removed the `ip` from `parent`, then when it handled `ip` would get `null`. This is fixed by always removing `jsonFieldName`, rather than `bqFieldName`.

File: ingestion-sink/src/main/java/com/mozilla/telemetry/ingestion/sink/transform/PubsubMessageToObjectNode.java [hunk 2]
```diff
@@ -456,10 +453,12 @@ private void expandMapType(String jsonFieldName, ObjectNode value, Field field,
...
       final ArrayNode unmapped = Json.createArrayNode();
       value.fields().forEachRemaining(e -> {
-        ObjectNode kv = Json.createObjectNode().put(FieldName.KEY, e.getKey());
+        ObjectNode kv = Json.createObjectNode();
         valueFieldOption
             .ifPresent(valueField -> processField(e.getKey(), valueField, e.getValue(), kv, props));
-        unmapped.add(kv);
+        // add key after processField so it can't be dropped due to e.getKey() matching
+        // FieldName.KEY when e.getValue() is null or empty or can't be coerced
+        unmapped.add(kv.put(FieldName.KEY, e.getKey()));
```
Comment (relud) [inline ingestion-sink/src/main/java/com/mozilla/telemetry/ingestion/sink/transform/PubsubMessageToObjectNode.java:461]: previously this wouldn't remove data from `kv` because `valueField.getName()` would never match `FieldName.KEY`, but now we have to make sure `kv` is empty when passed to `processField` because `e.getKey()` could be anything.

File: ingestion-sink/src/main/java/com/mozilla/telemetry/ingestion/sink/transform/PubsubMessageToObjectNode.java (hunk 1 above)
Comment (jklukas) [reply ingestion-sink/src/main/java/com/mozilla/telemetry/ingestion/sink/transform/PubsubMessageToObjectNode.java:269]: Do we need to make similar adjustments to `PubsubMessageToTableRow` to support the batch backfill case?

Comment (relud) [reply ingestion-sink/src/main/java/com/mozilla/telemetry/ingestion/sink/transform/PubsubMessageToObjectNode.java:269]: I'll start a follow-up PR to move `PubsubMessageToObjectNode` to `ingestion-core` and replace `PubsubMessageToTableRow`

File: ingestion-sink/src/test/resources/testdata/payload-format-expected.ndjson [hunk 3]
```diff
@@ -23,3 +23,5 @@
 {"additional_properties":{},"test_nested_list":[{"list":["a","b","c"]}],"test_nested_csv":[{"list":"a,b,c"}],"test_list":["a","b","c"]}
 {"additional_properties":{},"test_nested_list":[{}]}
 {"additional_properties":{}}
+{"additional_properties":{"test_int64_":"invalid"},"test_int64":8}
```
Comment (jklukas) [inline ingestion-sink/src/test/resources/testdata/payload-format-expected.ndjson:26]: This result isn't making sense to me. Does the `8` value win because it's processed last?

Comment (relud) [reply ingestion-sink/src/test/resources/testdata/payload-format-expected.ndjson:26]: > This result isn't making sense to me.

This test case intentionally highlights behavior that may be unexpected. I've filed #1298 to follow up on this.

> Does the `8` value win because it's processed last?

yes, because both fields map to `test_int64` and contain valid data, both fields are written to there, with the later values writing over earlier values.
