### PR TITLE
Fix #1670 - Check for existence of jwe_mappings in rally decoder 

### LINKED ISSUE #1670: Error message from worker: java.lang.NullPointerException com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:188)
/CC @Dexterp37

```
2021-04-29 08:52:02.703 GMT
Error message from worker: java.lang.NullPointerException com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:188) com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:114) org.apache.beam.sdk.transforms.Contextful.lambda$fn$36334a93$1(Contextful.java:112) org.apache.beam.sdk.transforms.FlatMapElements$FlatMapWithFailures$MapFn.processElement(FlatMapElements.java:344) java.lang.NullPointerException com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:188) com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:114) org.apache.beam.sdk.transforms.Contextful.lambda$fn$36334a93$1(Contextful.java:112) org.apache.beam.sdk.transforms.FlatMapElements$FlatMapWithFailures$MapFn.processElement(FlatMapElements.java:344)
```

https://github.com/mozilla/gcp-ingestion/blob/main/ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/rally/DecryptRallyPayloads.java#L188

This is throwing a `NullPointerException` which definitely isn't correct, but it looks like it was just going to throw a slightly more descriptive error anyway. AFAICT this is a code or schemas issue (or both). Certainly input data shouldn't be able to render the decoder unresponsive.

### PR DESCRIPTION
**Pull request by acmiyaguchi**
Fixes #1670

### CODE REVIEW

File: ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/rally/DecryptRallyPayloads.java [hunk 1]
```diff
@@ -185,7 +185,7 @@ private void decryptAndReplace(PrivateKey key, JsonNode json, List<JweMapping> m
       }
 
       final PipelineMetadata meta = pipelineMetadataStore.getSchema(attributes);
-      if (meta.jwe_mappings().isEmpty()) {
+      if (meta.jwe_mappings() == null || meta.jwe_mappings().isEmpty()) {
```
Comment (jklukas) [inline ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/rally/DecryptRallyPayloads.java:188]: It looks like Apache Commons has a `MapUtils.isEmpty(meta.jwe_mappings())` that handles the null case in a single call, but this is also fine.

**Review by jklukas — APPROVED** [review]
👍 The test here is nice.

File: ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/rally/DecryptRallyPayloads.java (hunk 1 above)
Comment (acmiyaguchi) [reply ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/rally/DecryptRallyPayloads.java:188]: I'm going to stick with this, it's easy enough to reason about without pulling in a new import.
