### PR TITLE
Fix DecoderOptions.parse 

### LINKED ISSUE #101: Fix DecoderOptions.parse
An exception occured while executing the Java class. Method [parse] has multiple definitions [public static com.mozilla.telemetry.decoder.DecoderOptions$Parsed com .mozilla.telemetry.decoder.DecoderOptions.parse(com.mozilla.telemetry.decoder.DecoderOptions), public static com.mozilla.telemetry.options.SinkOptions$Parsed com.mozilla.telemetry.options.SinkOptions.parse(com.mozilla.telemetry.options.SinkOptions)] with different return types for [com.mozilla.telemetry.decoder.DecoderOptions]. -> [Help 1]

### PR DESCRIPTION
**Pull request by jklukas**
Fixes #101 

Also adds DecoderMainTest to exercise DecoderOptions.

### CODE REVIEW

File: ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/DecoderOptions.java [hunk 1]
```diff
@@ -79,17 +79,17 @@
...
     return parsed;
   }
 
   /**
    * Set all the derived fields of a {@link DecoderOptions.Parsed} instance.
    */
-  static void enrich(Parsed options) {
-    SinkOptions.enrich(options);
+  static void enrichDecoderOptions(Parsed options) {
+    SinkOptions.enrichSinkOptions(options);
```
Comment (relud) [inline ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/DecoderOptions.java]: I think we can drop the `SinkOptions.` here now?

File: ingestion-beam/src/test/java/com/mozilla/telemetry/DecoderMainTest.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        "--outputFileFormat=json",
+        "--outputType=file",
+        "--output=" + output,
+        "--errorOutputType=file",
+        "--errorOutput=" + errorOutput,
+        "--geoCityDatabase=GeoLite2-City.mmdb",
+        "--seenMessagesSource=none"
+    });
+
+    List<String> errorOutputLines = Lines.files(outputPath + "/error*.ndjson");
```
Comment (relud) [inline ingestion-beam/src/test/java/com/mozilla/telemetry/DecoderMainTest.java]: I think `outputPath + "/error*.ndjson"` -> `errorOutput + "*.ndjson"` is more clear (I was confused at first why we used `outputPath` for `errorOutputLines`)

File: ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/DecoderOptions.java (hunk 1 above)
Comment (jklukas) [reply ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/DecoderOptions.java]: IntelliJ tells me "Static method may be invoked on containing interface class only", so looks like we need to qualify it. Inheritance of static methods seems like a bit of an ugly corner of Java's type system.
