### PR TITLE
Normalize paths in SchemaStore to support casing variants

### LINKED ISSUE #744: Loading to BQ fails for doctypes with underscores
[As mentioned in the GCP migration validation document](https://docs.google.com/a/mozilla.com/document/d/14UoZGAI2CgMQW4qeXIX5Bj9nq2kvfCUaONiNknXXxYE/edit?disco=AAAADV_ZM9w), we are seeing errors that fenix bookmarks_sync pings are being dropped with errors that show no appropriate schema exists in the schema store.

The table does exist, but our logic for the schema store assumes that pings have hyphenated names rather than underscores.

We may want to build validation into mozilla-pipeline-schemas at this point to prevent deviation from naming conventions. To solve the immediate problem, we could alias the existing schemas to new places, or we could update the gcp-ingestion code.

I am inclined to pursue an m-p-s-based solution.

cc @relud @whd

### PR DESCRIPTION
**Pull request by jklukas**
Closes #744

Also see https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/387 for discussion of longer-term solutions to avoid this complexity.

### CODE REVIEW

File: ingestion-beam/src/test/java/com/mozilla/telemetry/schemas/JSONSchemaStoreTest.java [hunk 1]
```diff
@@ -39,6 +39,8 @@ public void testDocTypeExists() {
     JSONSchemaStore store = JSONSchemaStore.of(SCHEMAS_LOCATION, EMPTY_ALIASING_CONFIG_LOCATION);
     assertTrue(store.docTypeExists("telemetry", "main"));
     assertTrue(store.docTypeExists("telemetry", "update"));
+    assertTrue(store.docTypeExists("telemetry", "untrustedModules"));
```
Comment (whd) [inline ingestion-beam/src/test/java/com/mozilla/telemetry/schemas/JSONSchemaStoreTest.java]: Shouldn't we test BigQuerySchemaStore? The new case we're resolving is with e.g. `bookmarks_sync` on BQ output. For test purposes they amount to the same thing I suppose (in the current implementation, but I have thoughts on that in the MPS PR).

Comment (jklukas) [reply ingestion-beam/src/test/java/com/mozilla/telemetry/schemas/JSONSchemaStoreTest.java]: The BigQueryIntegrationTest does effectively test this behavior for the BigQuerySchemaStore, but I can understand pushback for more unit testing.
