### PR TITLE
Fix #1280 -  Fail early on empty metadataLocation when Pioneer is enabled

### LINKED ISSUE #1280: NullPointerException on empty metadataLocation when Pioneer is enabled
The Pioneer decoder will fail when `--pioneerEnabled` is set and `--pioneerMetadataLocation` is unset on the first input.

```
Error message from worker: java.lang.NullPointerException java.util.regex.Matcher.getTextLength(Matcher.java:1283) java.util.regex.Matcher.reset(Matcher.java:309) java.util.regex.Matcher.<init>(Matcher.java:229) java.util.regex.Pattern.matcher(Pattern.java:1093) org.apache.beam.sdk.io.FileSystems.parseScheme(FileSystems.java:447) org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.Iterators$6.transform(Iterators.java:785) org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:244) org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:230) org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.FluentIterable.toSet(FluentIterable.java:647) org.apache.beam.sdk.io.FileSystems.getOnlyScheme(FileSystems.java:437) org.apache.beam.sdk.io.FileSystems.match(FileSystems.java:120) org.apache.beam.sdk.io.FileSystems.matchSingleFileSpec(FileSystems.java:184) com.mozilla.telemetry.util.BeamFileInputStream.open(BeamFileInputStream.java:15) com.mozilla.telemetry.util.KeyStore.loadAllKeys(KeyStore.java:75) com.mozilla.telemetry.util.KeyStore.ensureKeysLoaded(KeyStore.java:115) com.mozilla.telemetry.util.KeyStore.getKey(KeyStore.java:36) com.mozilla.telemetry.decoder.DecryptPioneerPayloads$Fn.apply(DecryptPioneerPayloads.java:113) com.mozilla.telemetry.decoder.DecryptPioneerPayloads$Fn.apply(DecryptPioneerPayloads.java:87) org.apache.beam.sdk.transforms.Contextful.lambda$fn$36334a93$1(Contextful.java:112) org.apache.beam.sdk.transforms.FlatMapElements$FlatMapWithFailures$MapFn.processElement(FlatMapElements.java:341)
```

This is caused by an issue in the following section:

https://github.com/mozilla/gcp-ingestion/blob/a6928fb089f1652856147c4605df715f327edfcd/ingestion-beam/src/main/java/com/mozilla/telemetry/util/KeyStore.java#L75-L81

This should be solved by forcing `pioneerMetadataLocation` to be set if `pioneerEnabled` is set, otherwise fail. Additionally, the pipeline should not fail on a NullPointerException.

### PR DESCRIPTION
**Pull request by acmiyaguchi**
This fixes #1280 by throwing an `IllegalArgumentException` when the metadataLocation is not properly.

### CODE REVIEW

File: ingestion-beam/src/main/java/com/mozilla/telemetry/util/KeyStore.java [hunk 1]
```diff
@@ -49,6 +49,11 @@ public static KeyStore of(String metadataLocation, boolean kmsEnabled) {
   private KeyStore(String metadataLocation, boolean kmsEnabled) {
     this.metadataLocation = metadataLocation;
     this.kmsEnabled = kmsEnabled;
+
+    // throw immediately if the keyStore is misconfigured
+    if (metadataLocation == null) {
+      throw new IllegalArgumentException("Metadata location is missing.");
+    }
```
Comment (scholtzan) [inline ingestion-beam/src/main/java/com/mozilla/telemetry/util/KeyStore.java:56]: I guess this check could be done before the assignments, but this way is also fine.
